name: Test
on: [pull_request]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run format test
        run: make test-format
      - name: Run lint test
        run: make test-lint
      - name: Run types test
        run:  make test-types
      - name: Run license test
        run: make test-license
      - name: Run tests
        run: make test
